config/routes.rb
	Rails.application.routes.draw do
  devise_for :customers, controllers: { registrations: "registrations" }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :customers
resources :investments
resources :schemes
root 'customers#index'
end

app/models/amc.rb
class Amc < ApplicationRecord
	has_many :schemes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :investments
	has_many :schemes, through: :investments
	has_one :total
end

app/models/investment.rb
class Investment < ApplicationRecord
	belongs_to :customer 
	belongs_to :scheme
end

app/models/nav.rb
class Nav < ApplicationRecord
	belongs_to :scheme
end

app/models/scheme.rb
class Scheme < ApplicationRecord
	has_many :investments
	belongs_to :amc
	has_many :customers, through: :investments
	has_many :navs
end

app/models/total.rb
class Total < ApplicationRecord
	belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @cs = Investment.where(customer_id: current_customer)
  
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit!
    end




end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: [:show, :edit, :update, :destroy]

  # GET /investments
  # GET /investments.json
  def index
    @investments = Investment.all
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
   
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment.destroy
    respond_to do |format|
      format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.require(:investment).permit(:scheme_id, :customer_id, :date, :amount)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	private

  def sign_up_params
    params.require(:customer).permit(:name,:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:customer).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/schemes_controller.rb
class SchemesController < ApplicationController
	def index
   @schemes = Scheme.all
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/schemes_helper.rb
module SchemesHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/_new_user_page.html.erb


<div class="jumbotron">
<h1>You Are New User...</h1>
<h2>You have to... </h2>
<%= link_to "sign up",new_customer_registration_path,class: "btn btn-primary",style: "color:white" %>
or
<%= link_to "log in",new_customer_session_path,class: "btn btn-primary",style: "color:white"  %></div>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<% if customer_signed_in? %>

<p id="notice"><%= notice %></p>

<h1>Customers</h1>
 <div>Signed in as... <%= current_customer.email %></div>
  <div>Signed in as... <%= current_customer.name %></div>
  <div>Signed in as ID no.... <%= current_customer.id %></div>
<%= link_to '<button type="button">Invest</button>'.html_safe, new_investment_path %>
<h1>Investments</h1>

<table>

  <thead>
    <tr>
      <th>Scheme</th>
    
      <th> Date</th>
      <th>&nbsp;&nbsp;&nbsp;Price</th>
       <th>&nbsp;&nbsp;&nbsp;nav</th>
        <th> &nbsp;&nbsp;&nbsp;units</th>
        <th> &nbsp;&nbsp;&nbsp;Todays nav</th>
        <th>  &nbsp;&nbsp;&nbsp;value </th>
      <th colspan="15"></th>
    </tr>
  </thead>

  <tbody>
    <% @cs.each do |investment| %>
      <tr>
        <td><%= investment.scheme.name %></td>
       
        <td><%= investment.date %></td>
        <td>&nbsp;&nbsp;&nbsp;<%= investment.amount %></td>
               <%  a= investment.id %>
       <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
       <%=  Investment.find(a).scheme.navs.order("date desc").where("DATE(date) BETWEEN ? AND ?",'2010-02-01', investment.date).first.price %></td>
           <% b= investment.amount %>
           <%c=Investment.find(a).scheme.navs.order("date desc").where("DATE(date) BETWEEN ? AND ?",'2010-02-01', investment.date).first.price %>
          <td> &nbsp;&nbsp;&nbsp; 
             
         <%= number_with_precision(b.to_f/c, :precision => 2)  %> </td>
         <td> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=  Investment.find(a).scheme.navs.order("date desc").first.price %></td>
          <%  d=Investment.find(a).scheme.navs.order("date desc").first.price %>
          <td>&nbsp;&nbsp;&nbsp;<%= number_to_currency(d*(b.to_f/c)) %></td>
      </tr>
    <% end %>
    
  </tbody>

</table>


<% else %>
<%= render 'new_user_page'%>

<% end %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/investments/_form.html.erb
<%= form_for(investment) do |f| %>
  <% if investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
      <% investment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scheme_id %>
   
    <%= f.collection_select :scheme_id, Scheme.all, :id, :name %>
   
  </div>

  <div class="field">
    <%=f.label :customer_id %>
  
     <%=f.hidden_field :customer_id, :value => current_customer.id %>
  <%= current_customer.name %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
        
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', customers_path %>

app/views/investments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investments</h1>

<table>
  <thead>
    <tr>
      <th>Scheme</th>
      <th>Customer</th>
      <th>Date</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investments.each do |investment| %>
      <tr>
        <td><%= investment.scheme_id %></td>
        <td><%= investment.customer_id %></td>
        <td><%= investment.date %></td>
        <td><%= investment.amount %></td>
        <td><%= link_to 'Show', investment %></td>
        <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
        <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment', new_investment_path %>

app/views/investments/new.html.erb
<h1>New Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Back', customers_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scheme:</strong>
  <%= @investment.scheme_id %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @investment.customer_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @investment.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @investment.amount %>
</p>

<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <title>Fund</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Scheme list",schemes_path,class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">

      <li><%= link_to "Sign Up", new_customer_registration_path%></li>
      <%if current_customer.present? %>
      <li><%= link_to "log out", destroy_customer_session_path%></li>
      <%else%>
      <li><%= link_to "sign in", new_customer_session_path%></li>
      <% end %>
    </ul>
</div>
</nav>
		<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/schemes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schemes</h1>

<table>
  <thead>
    <tr>
      <th>Scheme_id</th>
      <th>Scheme_name</th>
      <th>Year</th>
      <th>Minimum</th>
       <th>Lockin</th>
       <th>Amc_id</th>
      <th colspan="40"></th>
    </tr>
  </thead>

  <tbody>
    <% @schemes.each do |scheme| %>
      <tr>
        <td><%= scheme.id %></td>
        <td><%= scheme.name %></td>
        <td><%= scheme.year %></td>
        <td><%= scheme.minimum %></td>
        <td><%= scheme.lockin %></td>
         <td><%= scheme.amc_id %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>